### PR TITLE
Fix account close

### PR DESCRIPTION
**Pull request by keviny22**
@moofish32 could you review this change please. This is to address https://github.com/intuit/aws_account_utils/issues/19

and

https://github.com/intuit/aws_account_utils/issues/16

### CODE REVIEW

**Comment by moofish32** [comment]
@keviny22 -- we are just skipping 0.1.4? I am ok with that and the static inspection looks correct.

**Comment by keviny22** [comment]
@moofish32 0.1.4 is the current version, the Changelog wasnt updated for that version

**Comment by jpenvose** [comment]
Tested successfully with our PCCO sunset utility.

**Comment by keviny22** [comment]
@moofish32 This is ready for a merge if you are good with it.

**Comment by keviny22** [comment]
@moofish32 ping

**Pull request merged**
